version: '3.8'
services:
  Backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./Backend:/app
    env_file:
      - ./Backend/.env
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: