name: CI/CD
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build Backend
        run: cd Backend && npm run build
      - name: Build Docker images
        run: | 
          docker build -t backend-image:latest -f Backend/Dockerfile .
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker images
        run: | 
          docker push backend-image:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Kubernetes
        run: kubectl apply -f infra/kubernetes/Backend
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}